// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwbomdzrznyhyugiqbto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13Ym9tZHpyem55aHl1Z2lxYnRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDQzOTcsImV4cCI6MjA2NzYyMDM5N30.7MMiQ714iRLpGxnnUpKLNvzSI8TKUdC7WIlYuy_w3xM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});